routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'AdminController@index')->name('home');
Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('dispute-user.edit');

Route::resource('users', 'Resource\UserResource');
Route::resource('transporters', 'Resource\TransporterResource');
Route::resource('dispute-user', 'Resource\DisputeUserResource');
Route::resource('categories', 'Resource\CategoryResource');
Route::get('subcategory', 'Resource\CategoryResource@subcategory');
Route::resource('categories.products', 'Resource\ProductResource');
Route::resource('products', 'Resource\ProductResource');
Route::delete('productimage/{id}', 'Resource\ProductResource@imagedestroy')->name('productimage.destroy');
Route::resource('orders', 'Resource\OrderResource');
Route::resource('shops', 'Resource\ShopResource');
Route::get('/reasons', 'AdminController@reasons')->name('reasons');;
Route::get('/reason_create', 'AdminController@reason_create')->name('reason_create');;
Route::post('/reason_store', 'AdminController@reason_store')->name('reason_store');;
Route::get('/reason_edit/{id}', 'AdminController@reason_edit')->name('reason_edit');;
Route::post('/reason_update/{id}', 'AdminController@reason_update')->name('reason_update');;
Route::delete('/reason_destroy/{id}', 'AdminController@reason_destroy')->name('reason_destroy');;
Route::resource('zones', 'Resource\ZoneResource');
Route::resource('cuisines', 'Resource\CuisineResource');
Route::resource('demoapp', 'ManageappController');
Route::resource('promocodes', 'Resource\PromocodeResource');
Route::resource('emailtemplate', 'Resource\EmailTemplateResource');
Route::resource('translation', 'Resource\TranslationResource');
Route::get('disputes/{name}', 'Resource\DisputeResource@index');
Route::resource('dispute', 'Resource\DisputeResource');
Route::resource('banner', 'Resource\ShopBannerResource');
Route::resource('notice', 'Resource\NoticeBoardResource');
Route::resource('disputehelp', 'Resource\DisputeHelpResource');
Route::get('/settings', 'AdminController@settings')->name('settings');;
Route::post('/settings', 'AdminController@settings_store')->name('settings.store');;
//Route::get('/accsetting', 'AdminController@account_setting')->name('accsetting');;
Route::post('/setting/add', 'AdminController@AccountSettingStore')->name('accsetting.store');;

Route::get('/send/push', 'AdminController@push')->name('push');
Route::post('/send/push', 'AdminController@send_push')->name('send.push');

Route::get('/chat','Resource\DisputeResource@chatWithUser');

Route::post('/pages', 'AdminController@pages')->name('pages.update');

//pages

Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/disclaimer', 'AdminController@disclaimer')->name('disclaimer');
Route::post('/disclaimer_update', 'AdminController@disclaimer_update')->name('disclaimer_update');
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::get('/faq', 'AdminController@faq')->name('faq');
Route::get('/about', 'AdminController@about')->name('about');
Route::get('/help', 'AdminController@help')->name('help');
Route::get('/refund', 'AdminController@refund')->name('refund');
Route::get('/queries', 'AdminController@queries')->name('queries');
Route::get('/otherterms', 'AdminController@otherterms')->name('otherterms');
Route::get('/contact', 'AdminController@contact')->name('contact');

Route::get('/leadres', 'AdminController@restuarant_leads')->name('leadres');
Route::get('/newsletter', 'AdminController@newsletter_leads')->name('newsletter');
Route::get('/enquiry_delivery', 'AdminController@enquiry_delivery')->name('enquiry_delivery');


Route::resource('addons', 'Resource\AddonsResource');
Route::get('transporters-shift', 'Resource\TransporterResource@shiftdetails');

Route::post('/remove/product/images', 'Resource\ProductResource@remove_images')->name('remove_images');
Route::post('/remove/category/images', 'Resource\CategoryResource@remove_images')->name('product.remove_images');

routes/user.php
<?php

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'UserController@index')->name('home');

routes/web.php
|--------------------------------------------------------------------------
*/
//abort(404, 'The resource you are looking for could not be found');
Route::get('/', 'WelcomeController@home');


Route::get('privacy', function () {
    $page = 'privacy';
    $title = 'Privacy Policy';
    return view('static', compact('page', 'title'));
});

Route::get('aboutus', function () {
    $page = 'about';
    $title = 'About Us';
    return view('static', compact('page', 'title'));
});

Route::get('terms', function () {
    $page = 'terms';
    $title = 'Terms And Condition';
    return view('static', compact('page', 'title'));
});


// Route::get('faq', function () {
//     $page = 'faq';
//     $title = 'FAQ';
//     return view('static', compact('page', 'title'));
// });


Route::get('contact', function () {
    $page = 'contact';
    $title = 'Contact Us';
    return view('static', compact('page', 'title'));
});

Route::get('help', function () {
    $page = 'help';
    $title = 'Help';
    return view('static', compact('page', 'title'));
});

Route::get('refund', function () {
    $page = 'refund';
    $title = 'Refund';
    return view('static', compact('page', 'title'));
});

Route::get('otherterms', function () {
    $page = 'otherterms';
    $title = 'Other Terms';
    return view('static', compact('page', 'title'));
});


/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/search','WelcomeController@search');
Route::get('/enquiry-delivery','UserController@delivery');
Route::post('/enquiry-delivery','UserController@delivery_store');

Route::get('/ebs/payment/{id}','EbsPaymentController@initiate_payment');


Route::get('auth/facebook', 'SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'SocialLoginController@handleGoogleCallback');

Route::post('/social/login','SocialLoginController@loginWithSocial');

Route::get('/pushnotification', function () {
    $message = PushNotification::Message("Push Remote Rich Notifications",
        array(
            'badge' => 1,
            'sound' => 'example.aif',
            'content-available' => 1,
            'media-url' => 'https://i.imgur.com/t4WGJQx.jpg',
            'actionLocKey' => 'Action button title!',
            'locKey' => 'localized key',
            'locArgs' => array(
                'localized args',
                'localized args',
            ),
            'launchImage' => 'image.jpg',
            
            'custom' => array("custom data"=>array('we'=>1), "mutable-content" => 1,
                 "attachment-url"=> "https://raw.githubusercontent.com/Sweefties/iOS10-NewAPI-UserNotifications-Example/master/source/iOS10-NewAPI-UserNotifications-Example.jpg",
                "media-url" => "https://i.imgur.com/t4WGJQx.jpg" )
        )
    );   


    if(Request::has('andriod')){
    $test1 = \PushNotification::app('AndroidUser')
                ->to(Request::get('andriod'))
                ->send($message);
                dd($test1);
    }
    if(Request::has('iosuser')){
     $test = \PushNotification::app('IOSUser')
                ->to(Request::get('iosuser'))
                ->send($message);
                
                dd($test);
    }
    if(Request::has('iosprovider')){
    $test = \PushNotification::app('IOSProvider')
                ->to(Request::get('iosprovider'))
                ->send($message);
                dd($test);
    }
 });

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminAuth\LoginController@showLoginForm');
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'shop'], function () {
    Route::get('/', 'ShopAuth\LoginController@showLoginForm');
    Route::get('/login', 'ShopAuth\LoginController@showLoginForm');
    Route::post('/login', 'ShopAuth\LoginController@login');
    Route::post('/logout', 'ShopAuth\LoginController@logout');

    Route::get('/register', 'ShopAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'ShopAuth\RegisterController@register');

    Route::post('/password/email', 'ShopAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ShopAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'ShopAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ShopAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'transporter'], function () {
    Route::get('/login', 'TransporterAuth\LoginController@showLoginForm');
    Route::post('/login', 'TransporterAuth\LoginController@login');
    Route::post('/userlogin', 'TransporterAuth\LoginController@UserLogin');
    Route::get('/otplogin', 'TransporterAuth\LoginController@OtpLogin');
    Route::post('/logout', 'TransporterAuth\LoginController@logout');

    Route::post('/otp', 'TransporterAuth\RegisterController@OTP');
    Route::post('/verifyotp', 'TransporterAuth\RegisterController@CheckOtp');

    Route::get('/register', 'TransporterAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'TransporterAuth\RegisterController@register');

    Route::post('/password/email', 'TransporterAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'TransporterAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'TransporterAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'TransporterAuth\ResetPasswordController@showResetForm');

    Route::get('/home', 'TransporterController@index');
});

    Auth::routes();
    Route::get('login',function(){
        return redirect('/');
    });
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('register',function(){
        return redirect('/');
    });
    Route::get('/home', 'UserController@showhome');
    Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');
    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/user/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::post('shopreg', 'ShopController@register')->name('register');
    Route::post('newsletter', 'WelcomeController@newsletter')->name('newsletter');

    Route::post('/otp', 'Auth\RegisterController@OTP');
    Route::get('/dashboard', 'UserResource\OrderResource@orderprogress');
    Route::get('/profile', 'UserResource\ProfileController@index');
    Route::post('/profile', 'UserResource\ProfileController@update');
    Route::get('/changepassword', 'UserResource\ProfileController@changepassword');
    Route::post('/setpassword', 'UserResource\ProfileController@password');
    Route::resource('orders', 'UserResource\OrderResource');
    Route::resource('useraddress', 'UserResource\AddressResource');
    Route::get('/restaurants', 'UserResource\SearchResource@index');
    Route::get('/restaurant/details', 'UserResource\SearchResource@show');
    Route::post('mycart', 'UserResource\CartResource@addToCart');
    Route::post('addcart', 'UserResource\CartResource@store');
    Route::get('/clear/cart','UserResource\CartResource@clearCart');
    Route::get('/track/order/{id}','UserResource\SearchResource@ordertrack');
    Route::get('/product/details/{productid}/{cartId}/{shopname}/{productname}','UserResource\SearchResource@productDetails');
    // card
    Route::resource('card', 'Resource\CardResource');
    Route::get('payment', 'UserController@payment');
    Route::post('payment/confirm', 'PaymentController@payment');
    Route::any('cart/payment', 'UserController@order_payment');
    Route::get('wallet', 'UserController@wallet');
    Route::post('wallet', 'PaymentController@add_money');
    Route::post('/rating', 'UserResource\OrderResource@rate_review');
    Route::get('user/chat', 'UserResource\OrderResource@chatWithUser');
    Route::get('addons/{id}', 'Resource\ProductResource@show');
    Route::get('checkRipplePayment','PaymentController@checkRipplePayment');
    Route::get('checkEtherPayment','PaymentController@checkEtherPayment');
    // swiggy design
    Route::get('payments', 'UserController@payment');
    Route::resource('favourite', 'Resource\FavoriteResource');
    Route::get('offers', 'UserResource\SearchResource@offers');
    Route::get('legal', 'UserResource\SearchResource@legal');
    Route::get('faq', 'UserResource\SearchResource@faq');
    Route::get('queries', 'UserResource\SearchResource@queries');
    Route::post('wallet/promocode', 'UserResource\WalletResource@store');
    Route::post('/reorder', 'UserResource\OrderResource@reorder');
    
    //Route::get('/token','BraintreeTokenController@token');
    //Route::get('/payment','BraintreeTokenController@payment');
   // Route::post('/payment','BraintreeTokenController@do_payment');
  /*  Route::get('faq','WelcomeController@faq');
    Route::get('aboutus','WelcomeController@aboutus');

resources/views/shop/orders/create.blade.php
@extends('shop.layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12">
        <div class="card-box table-responsive">
            <h4 class="m-t-0 header-title">
                <b>Create User</b>
            </h4>
            <hr>
            <form class="form-horizontal" role="form" method="POST" action="{{ route('shop.users.store') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                    <label for="first_name" class="col-md-4 control-label">First Name</label>

                    <div class="col-md-6">
                        <input id="first_name" type="text" class="form-control" name="first_name" value="{{ old('first_name') }}" required autofocus>

                        @if ($errors->has('first_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('first_name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                    <label for="last_name" class="col-md-4 control-label">Last Name</label>

                    <div class="col-md-6">
                        <input id="last_name" type="text" class="form-control" name="last_name" value="{{ old('last_name') }}" required autofocus>

                        @if ($errors->has('last_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('last_name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif  
                    </div>
                </div>

                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password" required>

                        @if ($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                    <div class="col-md-6">
                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                    </div>
                </div>

                <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                    <label for="phone" class="col-md-4 control-label">Phone</label>

                    <div class="col-md-6">
                        <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

                        @if ($errors->has('phone'))
                            <span class="help-block">
                                <strong>{{ $errors->first('phone') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('avatar') ? ' has-error' : '' }}">
                    <label for="avatar" class="col-md-4 control-label">Avatar</label>

                    <div class="col-md-6">
                        <input type="file" accept="image/*" name="avatar" class="dropzone" id="avatar" aria-describedby="fileHelp">

                        @if ($errors->has('avatar'))
                            <span class="help-block">
                                <strong>{{ $errors->first('avatar') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Register
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/shop/orders/edit.blade.php
@extends('shop.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in as Admin!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/shop/orders/show.blade.php
@extends('shop.layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Dispatcher</h4>
        <br>
    </div>
</div>
<div class="row">
    <div class="col-md-4">

        <div class="card-box">
        	<h4 class="m-t-0 m-b-20 header-title"><b>User Details</b></h4>
            <div class="search-item">
                <div class="media">
                    <div class="media-left">
                    	<img class="media-object img-circle" src="{{ asset($Order->user->avatar ? : 'avatar.png') }}">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                    		{{ $Order->user->first_name }} {{ $Order->user->last_name }}
                        </h4>
                        <p>
                            <b>Phone:</b> 
                            <br>
                            <span>{{ $Order->user->phone }}</span>
                        </p>
                        <p>
                            <b>Email:</b> 
                            <br>
                            <span>{{ $Order->user->email }}</span>
                        </p>
                        <p>
                            <b>Delivery Address:</b>
                            <br>
                            <span class="text-muted">{{ $Order->address->map_address }}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Order</b></h4>
            
            <div class="inbox-widget nicescroll" style="overflow: hidden; outline: none; height: 200px;" tabindex="5000">
                @forelse($Order->items as $Item)
                <a href="{{ route('shop.products.show', $Item->id) }}">
                    <div class="inbox-item">
                        <div class="inbox-item-img">
                        	<img src="{{ asset($Item->product->images->isEmpty() ? 'avatar.png' : $Item->product->images[0]->url) }}">
                        </div>
                        <p class="inbox-item-author">{{ $Item->product->parent->name }}</p>
                        <p class="inbox-item-author">{{ $Item->product->name }}</p>
                        <p class="inbox-item-date">Qty : {{ $Item->quantity }}</p>
                    </div>
                </a>
                @empty
                <h4>No Items here, Looks like an invalid order</h4>
                @endforelse
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="box bg-white steps">
            <div class="box-block">
                <div class="s-numbers">
                    <div class="row">
                        <div class="col-xs-2">
                            <div class="s-number complete" id="step-1">
                                <span class="sn-icon">
                                    <i class="ti-check"></i>
                                </span>
                                <div class="sn-text">RECEIVED</div>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <div class="s-number text-xs-center" id="step-2">
                                <span class="sn-icon">2</span>
                                <div class="sn-text">PROCESSING</div>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <div class="s-number text-xs-center" id="step-3">
                                <span class="sn-icon">3</span>
                                <div class="sn-text">REACHED SHOP</div>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <div class="s-number text-xs-center" id="step-4">
                                <span class="sn-icon">4</span>
                                <div class="sn-text">PICKEDUP ORDER</div>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <div class="s-number text-xs-center" id="step-5">
                                <span class="sn-icon">5</span>
                                <div class="sn-text">ORDER ARRIVED</div>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <div class="s-number text-xs-right" id="step-6">
                                <span class="sn-icon">6</span>
                                <div class="sn-text">COMPLETED</div>
                            </div>
                        </div>
                    </div>
                </div>

                @if(in_array($Order->status, ['PROCESSING','REACHED','PICKEDUP','ARRIVED']) && status_next($Order->status))
                <hr>
                <h4>Update Status</h4>
                <form action="{{ route('admin.orders.update', $Order->id) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field("PATCH") }}
                    <input type="hidden" name="status" value="{{ status_next($Order->status) }}">
                    <button class="btn btn-info btn-block">
                        {{ status_next($Order->status) }}
                    </button>
                </form>
                @endif
            </div>
        </div>
    </div>

    <div class="col-md-8">
        @if(in_array($Order->status, ['RECEIVED']))
        <div class="card-box" style="max-height: 300px; overflow: auto;">
            <h4 class="m-t-0 m-b-20 header-title"><b>Transporters Nearby</b></h4>
            @forelse($Transporters as $Transporter)
            <div class="card-box inbox-widget col-xl-3 col-md-6 col-sm-6 col-xs-12" style="background-color: honeydew;">
                <div class="inbox-item" style="border: 0;">
                    <div class="col-xs-9">
                        <div class="inbox-item-img">
                            <img src="{{ asset( $Transporter->avatar ? : 'avatar.png') }}" class="img-circle" alt="" />
                        </div>
                        <p class="inbox-item-author">{{ $Transporter->first_name }} {{ $Transporter->last_name }}</p>
                        <p class="inbox-item-text">{{ $Transporter->email }}</p>
                        <p class="inbox-item-text">{{ $Transporter->phone }}</p>
                    </div>
                    <div class="col-xs-3">
                        <form action="{{ route('shop.orders.update', $Order->id) }}" id="assign-{{ $Transporter->id }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field("PATCH") }}
                            <input type="hidden" name="transporter_id" value="{{ $Transporter->id }}">
                            <button class="btn btn-info">
                                <i class="fa fa-2x fa-plus"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            @empty
            <div>
                <h4>No providers around!</h4>
            </div>
            @endforelse
        </div>
        @else
        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Transporter Details</b></h4>
            <div class="search-item">
                <div class="media">
                    <div class="media-left">
                        <a href="{{ route('shop.transporters.show', $Order->transporter->id) }}">
                            <img class="media-object img-circle" src="{{ asset($Order->transporter->avatar ? : 'avatar.png') }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                            <a href="{{ route('shop.transporters.show', $Order->transporter->id) }}">
                                {{ $Order->transporter->first_name }} {{ $Order->transporter->last_name }}
                            </a>
                        </h4>
                        <p>
                            <b>Phone:</b> 
                            <br>
                            <span>{{ $Order->transporter->phone }}</span>
                        </p>
                        <p>
                            <b>Email:</b> 
                            <br>
                            <span>{{ $Order->transporter->email }}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        @endif

        <div class="card-box">
            <h4 class="m-t-0 m-b-20 header-title"><b>Map</b></h4>
            
            <div id="gmaps" class="gmaps"></div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<style type="text/css">
	.media-object.img-circle {
		width: 64px;
		height: 64px;
	}
</style>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/admin/js/order-map.js') }}"></script>
<script type="text/javascript">
    var trip = {!! json_encode($Order) !!};
    function initMap() {
        if(['PROCESSING', 'REACHED', 'PICKEDUP', 'ARRIVED'].indexOf(trip.status) != -1) {
            ongoingInitialize(trip);
        } else if(trip.status == 'RECEIVED') {
            providers = {!! json_encode($Transporters) !!};
            assignProviderMap(providers, trip);
        } else {
            addressMapInitialize(trip);
        }
    }

    function updateStatus(status) {

        var step1 = $("#step-1");
        var step2 = $("#step-2");
        var step3 = $("#step-3");
        var step4 = $("#step-4");
        var step5 = $("#step-5");
        var step6 = $("#step-6");

        $('.s-number').each(function(index, element) {
            if($(element).hasClass('active')) {
                $(element).removeClass('active');
            }
            if($(element).hasClass('complete')) {
                $(element).removeClass('complete');
            }
        });

        switch(status) {
            case 'RECEIVED':
                complete([step1]);
                step2.addClass('active');
                break;
            case 'CANCELLED':
                complete([step1]);
                step2.addClass('active');
                break;
            case 'PROCESSING':
                complete([step1, step2]);
                step3.addClass('active');
                break;
            case 'REACHED':
                complete([step1, step2, step3]);
                step4.addClass('active');
                break;
            case 'PICKEDUP':
                complete([step1, step2, step3, step4]);
                step5.addClass('active');
                break;
            case 'ARRIVED':
                complete([step1, step2, step3, step4, step5]);
                step6.addClass('active');
                break;
            case 'COMPLETED':
                complete([step1, step2, step3, step4, step5, step6]);
                break;
            default:
                complete([step1]);
                step2.addClass('active');
        }

        function complete(elements) {
            $(elements).each(function(index, element) {
                $(element).addClass('complete');
                $(element).find('.sn-icon').html('<i class="ti-check"></i>');
            })
        }

    }
    updateStatus(trip.status);
</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAP_KEY') }}&libraries=places&callback=initMap" async defer></script>
@endsection