routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'AdminController@index')->name('home');
Route::get('{id}/profile', 'Resource\DisputeUserResource@edit')->name('dispute-user.edit');

Route::resource('users', 'Resource\UserResource');
Route::resource('transporters', 'Resource\TransporterResource');
Route::resource('dispute-user', 'Resource\DisputeUserResource');
Route::resource('categories', 'Resource\CategoryResource');
Route::get('subcategory', 'Resource\CategoryResource@subcategory');
Route::resource('categories.products', 'Resource\ProductResource');
Route::resource('products', 'Resource\ProductResource');
Route::delete('productimage/{id}', 'Resource\ProductResource@imagedestroy')->name('productimage.destroy');
Route::resource('orders', 'Resource\OrderResource');
Route::resource('shops', 'Resource\ShopResource');
Route::get('/reasons', 'AdminController@reasons')->name('reasons');;
Route::get('/reason_create', 'AdminController@reason_create')->name('reason_create');;
Route::post('/reason_store', 'AdminController@reason_store')->name('reason_store');;
Route::get('/reason_edit/{id}', 'AdminController@reason_edit')->name('reason_edit');;
Route::post('/reason_update/{id}', 'AdminController@reason_update')->name('reason_update');;
Route::delete('/reason_destroy/{id}', 'AdminController@reason_destroy')->name('reason_destroy');;
Route::resource('zones', 'Resource\ZoneResource');
Route::resource('cuisines', 'Resource\CuisineResource');
Route::resource('demoapp', 'ManageappController');
Route::resource('promocodes', 'Resource\PromocodeResource');
Route::resource('emailtemplate', 'Resource\EmailTemplateResource');
Route::resource('translation', 'Resource\TranslationResource');
Route::get('disputes/{name}', 'Resource\DisputeResource@index');
Route::resource('dispute', 'Resource\DisputeResource');
Route::resource('banner', 'Resource\ShopBannerResource');
Route::resource('notice', 'Resource\NoticeBoardResource');
Route::resource('disputehelp', 'Resource\DisputeHelpResource');
Route::get('/settings', 'AdminController@settings')->name('settings');;
Route::post('/settings', 'AdminController@settings_store')->name('settings.store');;
//Route::get('/accsetting', 'AdminController@account_setting')->name('accsetting');;
Route::post('/setting/add', 'AdminController@AccountSettingStore')->name('accsetting.store');;

Route::get('/send/push', 'AdminController@push')->name('push');
Route::post('/send/push', 'AdminController@send_push')->name('send.push');

Route::get('/chat','Resource\DisputeResource@chatWithUser');

Route::post('/pages', 'AdminController@pages')->name('pages.update');

//pages

Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/disclaimer', 'AdminController@disclaimer')->name('disclaimer');
Route::post('/disclaimer_update', 'AdminController@disclaimer_update')->name('disclaimer_update');
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::get('/faq', 'AdminController@faq')->name('faq');
Route::get('/about', 'AdminController@about')->name('about');
Route::get('/help', 'AdminController@help')->name('help');
Route::get('/refund', 'AdminController@refund')->name('refund');
Route::get('/queries', 'AdminController@queries')->name('queries');
Route::get('/otherterms', 'AdminController@otherterms')->name('otherterms');
Route::get('/contact', 'AdminController@contact')->name('contact');

Route::get('/leadres', 'AdminController@restuarant_leads')->name('leadres');
Route::get('/newsletter', 'AdminController@newsletter_leads')->name('newsletter');
Route::get('/enquiry_delivery', 'AdminController@enquiry_delivery')->name('enquiry_delivery');


Route::resource('addons', 'Resource\AddonsResource');
Route::get('transporters-shift', 'Resource\TransporterResource@shiftdetails');

Route::post('/remove/product/images', 'Resource\ProductResource@remove_images')->name('remove_images');
Route::post('/remove/category/images', 'Resource\CategoryResource@remove_images')->name('product.remove_images');

routes/user.php
<?php

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('/home', 'UserController@index')->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
//abort(404, 'The resource you are looking for could not be found');
Route::get('/', 'WelcomeController@home');


Route::get('privacy', function () {
    $page = 'privacy';
    $title = 'Privacy Policy';
    return view('static', compact('page', 'title'));
});

Route::get('aboutus', function () {
    $page = 'about';
    $title = 'About Us';
    return view('static', compact('page', 'title'));
});

Route::get('terms', function () {
    $page = 'terms';
    $title = 'Terms And Condition';
    return view('static', compact('page', 'title'));
});


// Route::get('faq', function () {
//     $page = 'faq';
//     $title = 'FAQ';
//     return view('static', compact('page', 'title'));
// });


Route::get('contact', function () {
    $page = 'contact';
    $title = 'Contact Us';
    return view('static', compact('page', 'title'));
});

Route::get('help', function () {
    $page = 'help';
    $title = 'Help';
    return view('static', compact('page', 'title'));
});

Route::get('refund', function () {
    $page = 'refund';
    $title = 'Refund';
    return view('static', compact('page', 'title'));
});

Route::get('otherterms', function () {
    $page = 'otherterms';
    $title = 'Other Terms';
    return view('static', compact('page', 'title'));
});


/*Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/search','WelcomeController@search');
Route::get('/enquiry-delivery','UserController@delivery');
Route::post('/enquiry-delivery','UserController@delivery_store');

Route::get('/ebs/payment/{id}','EbsPaymentController@initiate_payment');


Route::get('auth/facebook', 'SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'SocialLoginController@handleGoogleCallback');

Route::post('/social/login','SocialLoginController@loginWithSocial');

Route::get('/pushnotification', function () {
    $message = PushNotification::Message("Push Remote Rich Notifications",
        array(
            'badge' => 1,
            'sound' => 'example.aif',
            'content-available' => 1,
            'media-url' => 'https://i.imgur.com/t4WGJQx.jpg',
            'actionLocKey' => 'Action button title!',
            'locKey' => 'localized key',
            'locArgs' => array(
                'localized args',
                'localized args',
            ),
            'launchImage' => 'image.jpg',
            
            'custom' => array("custom data"=>array('we'=>1), "mutable-content" => 1,
                 "attachment-url"=> "https://raw.githubusercontent.com/Sweefties/iOS10-NewAPI-UserNotifications-Example/master/source/iOS10-NewAPI-UserNotifications-Example.jpg",
                "media-url" => "https://i.imgur.com/t4WGJQx.jpg" )
        )
    );   


    if(Request::has('andriod')){
    $test1 = \PushNotification::app('AndroidUser')
                ->to(Request::get('andriod'))
                ->send($message);
                dd($test1);
    }
    if(Request::has('iosuser')){
     $test = \PushNotification::app('IOSUser')
                ->to(Request::get('iosuser'))
                ->send($message);
                
                dd($test);
    }
    if(Request::has('iosprovider')){
    $test = \PushNotification::app('IOSProvider')
                ->to(Request::get('iosprovider'))
                ->send($message);
                dd($test);
    }
 });

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminAuth\LoginController@showLoginForm');
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'AdminAuth\RegisterController@register');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'shop'], function () {
    Route::get('/', 'ShopAuth\LoginController@showLoginForm');
    Route::get('/login', 'ShopAuth\LoginController@showLoginForm');
    Route::post('/login', 'ShopAuth\LoginController@login');
    Route::post('/logout', 'ShopAuth\LoginController@logout');

    Route::get('/register', 'ShopAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'ShopAuth\RegisterController@register');

    Route::post('/password/email', 'ShopAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ShopAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'ShopAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ShopAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'transporter'], function () {
    Route::get('/login', 'TransporterAuth\LoginController@showLoginForm');
    Route::post('/login', 'TransporterAuth\LoginController@login');
    Route::post('/userlogin', 'TransporterAuth\LoginController@UserLogin');
    Route::get('/otplogin', 'TransporterAuth\LoginController@OtpLogin');
    Route::post('/logout', 'TransporterAuth\LoginController@logout');

    Route::post('/otp', 'TransporterAuth\RegisterController@OTP');
    Route::post('/verifyotp', 'TransporterAuth\RegisterController@CheckOtp');

    Route::get('/register', 'TransporterAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'TransporterAuth\RegisterController@register');

    Route::post('/password/email', 'TransporterAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'TransporterAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'TransporterAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'TransporterAuth\ResetPasswordController@showResetForm');

    Route::get('/home', 'TransporterController@index');
});

    Auth::routes();
    Route::get('login',function(){
        return redirect('/');
    });
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::get('register',function(){
        return redirect('/');
    });
    Route::get('/home', 'UserController@showhome');
    Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.request');
    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/user/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');

    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::post('shopreg', 'ShopController@register')->name('register');
    Route::post('newsletter', 'WelcomeController@newsletter')->name('newsletter');

    Route::post('/otp', 'Auth\RegisterController@OTP');
    Route::get('/dashboard', 'UserResource\OrderResource@orderprogress');
    Route::get('/profile', 'UserResource\ProfileController@index');
    Route::post('/profile', 'UserResource\ProfileController@update');
    Route::get('/changepassword', 'UserResource\ProfileController@changepassword');
    Route::post('/setpassword', 'UserResource\ProfileController@password');
    Route::resource('orders', 'UserResource\OrderResource');
    Route::resource('useraddress', 'UserResource\AddressResource');
    Route::get('/restaurants', 'UserResource\SearchResource@index');
    Route::get('/restaurant/details', 'UserResource\SearchResource@show');
    Route::post('mycart', 'UserResource\CartResource@addToCart');
    Route::post('addcart', 'UserResource\CartResource@store');
    Route::get('/clear/cart','UserResource\CartResource@clearCart');
    Route::get('/track/order/{id}','UserResource\SearchResource@ordertrack');
    Route::get('/product/details/{productid}/{cartId}/{shopname}/{productname}','UserResource\SearchResource@productDetails');
    // card
    Route::resource('card', 'Resource\CardResource');
    Route::get('payment', 'UserController@payment');
    Route::post('payment/confirm', 'PaymentController@payment');
    Route::any('cart/payment', 'UserController@order_payment');
    Route::get('wallet', 'UserController@wallet');
    Route::post('wallet', 'PaymentController@add_money');
    Route::post('/rating', 'UserResource\OrderResource@rate_review');
    Route::get('user/chat', 'UserResource\OrderResource@chatWithUser');
    Route::get('addons/{id}', 'Resource\ProductResource@show');
    Route::get('checkRipplePayment','PaymentController@checkRipplePayment');
    Route::get('checkEtherPayment','PaymentController@checkEtherPayment');
    // swiggy design
    Route::get('payments', 'UserController@payment');
    Route::resource('favourite', 'Resource\FavoriteResource');
    Route::get('offers', 'UserResource\SearchResource@offers');
    Route::get('legal', 'UserResource\SearchResource@legal');
    Route::get('faq', 'UserResource\SearchResource@faq');
    Route::get('queries', 'UserResource\SearchResource@queries');
    Route::post('wallet/promocode', 'UserResource\WalletResource@store');
    Route::post('/reorder', 'UserResource\OrderResource@reorder');
    
    //Route::get('/token','BraintreeTokenController@token');
    //Route::get('/payment','BraintreeTokenController@payment');
   // Route::post('/payment','BraintreeTokenController@do_payment');

app/EmailTemplate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmailTemplate extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'template_name',
        'email_subject',
        'sender_name',
        'sender_email',
        'content'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at', 'deleted_at'
    ];

    /**
     * The services that belong to the user.
     */
    // public function pusage()
    // {
    //     return $this->belongsTo('App\PromocodeUsage','id','promocode_id');
    // }
    /**
     * Get the list of all categories along with subcategories and images.
     */
    // public function scopeUserPromo($query, $user_id = NULL)
    // {
    //     return $query->with(['pusage' => function($query) use ($user_id){
    //             return $query->where('user_id','==', $user_id)->where('STATUS','==','USED');
    //         }]);
    // }
}

resources/views/admin/emailtemplate/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Create Email Template</h3>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <form role="form" method="POST" action="{{ route('admin.emailtemplate.store') }}" enctype="multipart/form-data">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('template_name') ? ' has-error' : '' }}">
                    <label for="template_name">Template Name</label>

                    <input id="template_name" type="text" class="form-control" name="template_name" value="{{ old('template_name') }}" required autofocus>

                    @if ($errors->has('template_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('template_name') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('sender_name') ? ' has-error' : '' }}">
                    <label for="sender_name">Sender Name</label>

                    <input id="sender_name" type="text" class="form-control" name="sender_name" value="{{ old('sender_name') }}" required >

                    @if ($errors->has('sender_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('sender_name') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('sender_email') ? ' has-error' : '' }}">
                    <label for="sender_email">Sender Email</label>

                    <input id="sender_email" type="text" class="form-control" name="sender_email" value="{{ old('sender_email') }}" required >

                    @if ($errors->has('sender_email'))
                    <span class="help-block">
                        <strong>{{ $errors->first('sender_email') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('email_subject') ? ' has-error' : '' }}">
                    <label for="email_subject">Email Subject</label>

                    <input id="email_subject" type="text" class="form-control" name="email_subject" value="{{ old('email_subject') }}" required >

                    @if ($errors->has('email_subject'))
                    <span class="help-block">
                        <strong>{{ $errors->first('email_subject') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                    <label for="content">Email Content</label>

                    <textarea name="content" id="myeditor"></textarea>

                    @if ($errors->has('content'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content') }}</strong>
                    </span>
                    @endif
                </div>
                 <div class="col-xs-12 mb-2">
                    <a href="{{ route('admin.emailtemplate.index') }}" class="btn btn-warning mr-1">
                        <i class="ft-x"></i> Cancel
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('styles')
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script type="text/javascript">
    $('.datepicker').datepicker();
</script>
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
@endsection

resources/views/admin/emailtemplate/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Edit Email Template</h3>
    </div>
    <div class="card-body collapse in">
        <div class="card-block">
            <form role="form" method="POST" action="{{ route('admin.emailtemplate.update',$EmailTemplate->id) }}" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-group{{ $errors->has('template_name') ? ' has-error' : '' }}">
                    <label for="template_name">Template Name</label>

                    <input id="template_name" type="text" class="form-control" name="template_name" value="{{ old('template_name',$EmailTemplate->template_name) }}" required autofocus>

                    @if ($errors->has('template_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('template_name') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('sender_name') ? ' has-error' : '' }}">
                    <label for="sender_name">Sender Name</label>

                    <input id="sender_name" type="text" class="form-control" name="sender_name" value="{{ old('sender_name', $EmailTemplate->sender_name) }}" required >

                    @if ($errors->has('sender_name'))
                    <span class="help-block">
                        <strong>{{ $errors->first('sender_name') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('sender_email') ? ' has-error' : '' }}">
                    <label for="sender_email">Sender Email</label>

                    <input id="sender_email" type="text" class="form-control" name="sender_email" value="{{ old('sender_email', $EmailTemplate->sender_email) }}" required >

                    @if ($errors->has('sender_email'))
                    <span class="help-block">
                        <strong>{{ $errors->first('sender_email') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('email_subject') ? ' has-error' : '' }}">
                    <label for="email_subject">Email Subject</label>

                    <input id="email_subject" type="text" class="form-control" name="email_subject" value="{{ old('email_subject', $EmailTemplate->email_subject) }}" required >

                    @if ($errors->has('email_subject'))
                    <span class="help-block">
                        <strong>{{ $errors->first('email_subject') }}</strong>
                    </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                    <label for="content">Email Content</label>

                    <textarea name="content" id="myeditor" required>{{ old('content', $EmailTemplate->content) }}</textarea>

                    @if ($errors->has('content'))
                    <span class="help-block">
                        <strong>{{ $errors->first('content') }}</strong>
                    </span>
                    @endif
                </div>
                 <div class="col-xs-12 mb-2">
                    <a href="{{ route('admin.emailtemplate.index') }}" class="btn btn-warning mr-1">
                        <i class="ft-x"></i> Cancel
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('styles')
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('assets/admin/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script type="text/javascript">
    $('.datepicker').datepicker();
</script>
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
@endsection

resources/views/admin/emailtemplate/index.blade.php
@extends('admin.layouts.app')

@section('content')
 <!-- File export table -->
                <div class="row file">
                    <div class="col-xs-12">
                        <div class="card">
                            <div class="card-header">
                                @if(Setting::get('DEMO_MODE')==0)
                                <div class="col-md-12" style="height:50px;color:red;">
                                     ** Demo Mode : No Permission to Edit and Delete.
                                </div>
                                @endif
                                <h4 class="card-title">Email Templates</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                        <li><a href="{{ route('admin.emailtemplate.create') }}" class="btn btn-primary add-btn btn-darken-3">Add Email Template</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body collapse in">
                                <div class="card-block card-dashboard table-responsive">
                                    <table class="table table-striped table-bordered file-export">
                                        <thead>
                                            <tr>
                                                <th>S.no</th>
                                                <th>Template Name</th>
                                                <th>Subject</th>
                                                <th>Sender Email</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($EmailTemplates as $key=>$EmailTemplate)
                                                <tr>
                                                    <td>{{ $key+1 }}</td>
                                                    <td>{{ $EmailTemplate->template_name }}</td>
                                                    <td>{{ $EmailTemplate->email_subject }}</td>
                                                    <td>{{ $EmailTemplate->sender_email }}</td>
                                                    <td>
                                                        @if(Setting::get('DEMO_MODE')==1)
                                                        <a  class="table-btn btn btn-icon btn-success" href="{{ route('admin.emailtemplate.edit', $EmailTemplate->id) }}"><i class="fa fa-pencil-square-o"></i></a>
                                                        <button  class="table-btn btn btn-icon btn-danger" form="resource-delete-{{ $EmailTemplate->id }}" ><i class="fa fa-trash-o"></i></button> 
                                                        @endif
                                                        <form id="resource-delete-{{ $EmailTemplate->id }}" action="{{ route('admin.emailtemplate.destroy', $EmailTemplate->id)}}" method="POST">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- File export table -->


                 <!-- Menu List Modal Starts -->
    <div class="modal fade text-xs-left" id="menu-list">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h2 class="modal-title" id="myModalLabel1">Menu List</h2>
                </div>
                <div class="modal-body">
                    <div class="row m-0">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product Image</th>
                                        <th>Product Name</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">
                                            <div class="bg-img order-img" style="background-image: url(../assets/img/product-1.jpg);"></div>
                                        </th>
                                        <td>Burger Bistro</td>
                                        <td>$100</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Menu List Modal Ends -->
@endsection

resources/views/admin/emailtemplate/show.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in as Admin!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection